spring:
  application:
    name: shhdoc-api
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

upstage:
  api-key: ${UPSTAGE_API_KEY:}
  document-parse-url: ${UPSTAGE_DOCUMENT_PARSE_URL:https://api.upstage.ai/v1/document-digitization}
  document-classify-url: ${UPSTAGE_DOCUMENT_CLASSIFY_URL:https://api.upstage.ai/v1/document-classification/chat/completions}
  information-extract-url: ${UPSTAGE_INFORMATION_EXTRACT_URL:https://api.upstage.ai/v1/information-extraction/chat/completions}
  generate-url: ${UPSTAGE_GENERATE_URL:https://api.upstage.ai/v1/chat/completions}
